/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef mia_CONSTANTS_H
#define mia_CONSTANTS_H

#include "mia_types.h"

namespace scriptapi {

class miaConstants {
 public:
  miaConstants();

};

extern const miaConstants g_mia_constants;

} // namespace

#endif
