/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "mia_constants.h"

namespace scriptapi {

const miaConstants g_mia_constants;

miaConstants::miaConstants() {
}

} // namespace

